//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kategoriler()
        {
            this.tbl_Yemekler = new HashSet<tbl_Yemekler>();
        }
    
        public short Kategoriid { get; set; }
        public string KategoriAd { get; set; }
        public Nullable<short> KategoriAdet { get; set; }
        public string KategoriResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yemekler> tbl_Yemekler { get; set; }
    }
}
