//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GununYemegi
    {
        public short GununYemekid { get; set; }
        public string GununYemekad { get; set; }
        public string GununYemekMalzeme { get; set; }
        public string GununYemekTarif { get; set; }
        public Nullable<byte> GununYemekPuan { get; set; }
        public Nullable<System.DateTime> GununYemekTarih { get; set; }
    }
}
